name: AutoReferee
main: org.mctourney.AutoReferee.AutoReferee
version: 0.3

authors:
  - authorblues
  - TomShar

softdepend:
  - WorldEdit

commands:
  autoref:
    description: AutoReferee configuration
    permission: autoreferee.configure
    usage: /<command> save|stats|wincond|zones
  zone:
    description: Set a region's ownership
    permission: autoreferee.configure
    usage: /<command> <teamname>|start
  jointeam:
    description: Set player's team
    permission: autoreferee.referee
    usage: /<command> [teamname] [playername]
  leaveteam:
    description: Remove player's team
    permission: autoreferee.referee
    usage: /<command> [playername]
  ready:
    description: Prepare world for match
    permission: autoreferee.referee
    usage: /<command>