config-version: 2
console-log: true
auto-update: true

allow-ties: false

server-mode:
  online: false
  keyserver: server.mlm.net
  key: YOUR-KEY-GOES-HERE
  query-server: localhost

delay-seconds:
  ready: 15
  completed: 180

# all paths relative to the server-root
local-storage:
  match-summary: plugins/AutoReferee/summary
  local-database: plugins/AutoReferee/autoref.sdb

config-mode:
  tools:
    win-condition: GOLD_SPADE
    start-mechanism: GOLD_AXE
    protect-entities: GOLD_SWORD
