config-version: 2
console-log: true
auto-update: true

server-mode:
  online: false
  keyserver: server.mlm.net
  key: YOUR-KEY-GOES-HERE
  query-server: localhost

delay-seconds:
  ready: 15
  completed: 180

config-mode:
  tools:
    win-condition: GOLD_SPADE
    start-mechanism: GOLD_AXE
    protect-entities: GOLD_SWORD
