config-version: 1
keyserver: server.mlm.net

server-mode:
  console-log: true
  online: true
  server-key: YOUR-KEY-GOES-HERE

  server-list:
    - localhost
  delay-seconds:
    ready: 15
    completed: 180

config-mode:
  tools:
    win-condition: 284
    start-mechanism: 286
