name: AutoReferee
main: org.mctourney.AutoReferee.AutoReferee
version: 1.0
author: authorblues
load: startup

softdepend:
  - WorldEdit

commands:
  autoref:
    aliases: [ar, autoreferee]
    description: AutoReferee configuration
    permission: autoreferee.admin
    usage: /<command> [<action>] [args...]
    permission-message: Only admins have access to AutoReferee configuration.
  zone:
    description: Set a region's ownership
    permission: autoreferee.admin
    usage: /<command> <teamname>|start
  zones:
    description: Show a list of all zones
    permission: autoreferee.player
    usage: /<command> <teamname>|start
  matchinfo:
    description: Show info about current match
    permission: autoreferee.player
    usage: /<command>
  jointeam:
    aliases: [join, j]
    description: Set player's team
    permission: autoreferee.player
    usage: /<command> [<teamname>] [<playername>]
  leaveteam:
    aliases: leave
    description: Remove player's team
    permission: autoreferee.player
    usage: /<command> [<playername>]
  ready:
    description: Mark team as ready to play
    permission: autoreferee.player
    usage: /<command> [true|false|yes|no]
  viewinventory:
    aliases: vi
    description: View the inventory of the player
    permission: autoreferee.referee
    usage: /<command> <playername>
  artp:
    aliases: [atp]
    description: Teleport spectators safely
    permission: autoreferee.referee
    usage: /<command> [<options>] <target>

permissions:
  autoreferee.*:
    description: Access to all AutoReferee features
    default: op
    children:
      autoreferee.admin: true
  autoreferee.admin:
    description: AutoReferee administrators
    default: false
    children:
      autoreferee.configure: true
      autoreferee.referee: true
  autoreferee.configure:
    description: AutoReferee configuration
    default: false
  autoreferee.streamer:
    description: AutoReferee streamer
    default: false
    children:
      autoreferee.referee: true
  autoreferee.referee:
    description: AutoReferee referees
    default: false
    children:
      autoreferee.player: true
  autoreferee.player:
    description: AutoReferee players
    default: true
    children:
      bukkit.command.kill: false
