config-version: 1
keyserver: server.mlm.net

server-mode:
  console-log: true
  online: true
  server-key: YOUR-KEY-GOES-HERE

  server-list:
    - localhost

config-mode:
  autosave: true
  tools:
    win-condition: 284
